Algoritmo "15"
// Autor(a)    : Samuel Souza
// Data atual  : 14/05/2026
// 15) Crie um programa que leia o número de dias trabalhados em um mês e mostre o
// salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha R$25
// por hora trabalhada.

Var
   dias: inteiro
   salario: real

Inicio
     Escreva("Dias trabalhados: ")
     Leia(dias)
     salario <- dias * 200
     Escreva("Esse é o salário: R$", salario)
      


Fimalgoritmo