Algoritmo "2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Samuel Souza
// Data atual  : 09/05/2026
// 2) Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de boasvindas para ela:
// Ex:
// Qual é o seu nome? João da Silva
// Olá João da Silva, é um prazer te conhecer!
Var
   nome: caractere

Inicio
      Escreva("Qual é o seu nome? ")
      Leia(nome)
      Escreva("Olá ", nome, ", é um prazer te conhecer!")

Fimalgoritmo