Algoritmo "3"
// Autor(a)    : Samuel Souza
// Data atual  : 12/05/2026
// 3) Crie um programa que leia o nome e o salário de um funcionário, mostrando no
// final uma mensagem.
// Ex:
// Nome do Funcionário: Maria do Carmo
// Salário: 1850,45
// O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.
Var
   nome: Caractere
   salario: Real

Inicio
      Escreva("Nome do Funcionário: ")
      Leia(nome)
      Escreva("Salário: ")
      Leia(salario)
      Escreva("O funcionário ", nome, " tem um salário de R$",salario, " em Junho")


Fimalgoritmo