Algoritmo "4"
// Autor(a)    : Samuel Souza
// Data atual  : 12/05/2026
// 4) Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
// entre eles.
// Ex:
// Digite um valor: 8
// Digite outro valor: 5
// A soma entre 8 e 5 é igual a 13.
Var
   n1, n2, soma: Inteiro

Inicio
      Escreva("Digite um valor: ")
      Leia(n1)
      Escreva("Digite outro valor: ")
      Leia(n2)
      soma <- n1 + n2
      Escreva("A soma entre ",n1," e ",n2," é igual a ",soma)

Fimalgoritmo