Algoritmo "6"
// Autor(a)    : Samuel Souza
// Data atual  : 14/05/2026
// 6) Faça um programa que leia um número inteiro e mostre o seu antecessor e seu
// sucessor.
// Ex:
// Digite um número: 9
// O antecessor de 9 é 8
// O sucessor de 9 é 10
Var
   numero: Inteiro

Inicio
      Escreva("Digite um número: ")
      Leia(numero)
      Escreval("O antecessor de",numero," é", numero-1)
      Escreva("O sucessor de",numero," é", numero+1)


Fimalgoritmo