Algoritmo "7"
// Autor(a)    : Samuel Souza
// Data atual  : 14/05/2026
// 7) Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
// sua terça parte.
// Ex:
// Digite um número: 3.5
// O dobro de 3.5 é 7.0
// A terça parte de 3.5 é 1.16666

Var
   numero: Real

Inicio
      Escreva("Digite um número: ")
      Leia(numero)
      Escreval("O dobro de",numero," é", numero*2)
      Escreva("A terça parte de",numero," é", numero/3)

Fimalgoritmo